package com.stetel.printerdemo;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.stetel.printer.Printer;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MainActivity extends AppCompatActivity {
    private EditText emailAddressEdt;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        emailAddressEdt = findViewById(R.id.emailAddress);
        findViewById(R.id.sendEmailBtn).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String emailAddress = emailAddressEdt.getText().toString();
                if (TextUtils.isEmpty(emailAddress)) {
                    Toast.makeText(MainActivity.this, "Add an email address first", Toast.LENGTH_LONG).show();
                } else {
                    Printer.sendEmailWithLogFile(
                            MainActivity.this,
                            "Select the app for sending the email",
                            emailAddress,
                            "Printer log file",
                            "Attached the log file generated by the Printer demo app.");
                }
            }
        });

        Printer.i("Log file: ", Printer.getLogFile());

        Printer.i("Hello world!");

        Printer.i("Current date is ", new Date());

        List<String> stringList = new ArrayList<>();
        stringList.add("one");
        stringList.add("two");
        stringList.add("three");
        Printer.i("List: ", stringList);

        Map<String, Integer> stringIntegerMap = new HashMap<>();
        stringIntegerMap.put("one", 1);
        stringIntegerMap.put("two", 2);
        stringIntegerMap.put("three", 3);
        Printer.i("Map: ", stringIntegerMap);

        try {
            int foo = 2/0;
        } catch (Exception e) {
            Printer.e("Dividing by zero: ", e);
        }
    }
}
